---
- hosts: all
  become: true
  tasks:
    - name: APT | Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes cache_valid_time=3600

    - name: APT | Ensuare installed packages
      apt:
        state: present
        name:
          - mc
          - nginx-extras
          - php7.4-fpm

    - name: NGINX | Config
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: 
        - restart nginx 
    
    - name: PHP-FPM | Config
      template:
        src: www.conf
        dest: /etc/php/7.4/fpm/pool.d/www.conf
      notify: 
        - restart php-fpm

    - name: PHP | Config
      template:
        src: php.ini
        dest: /etc/php/7.4/fpm/php.ini
      notify: 
        - restart php-fpm
    
  handlers:
    - name: restart nginx 
      service: name=nginx state=restarted 
    - name: restart php-fpm
      service: name=php7.4-fpm state=restarted